b2bonline/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from main.views.CartViews import *
from main.views.CatalogViews import *
from main.views.SettingsViews import *
from main.views.OrderViews import *
from main.views.CommonViews import *

from reference.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/reference/import_reference/', login_required(ImportProducts.as_view())),
    
    url(r'^$', LoginView.as_view()),
    url(r'^logout/', login_required(logout_view)),
    
    url(r'^search/', login_required(SearchView.as_view())),
    url(r'^catalog/', login_required(CatalogView.as_view())),
    url(r'^get_notify_status', login_required(get_notify_status)),
    url(r'^set_notify_status', login_required(set_notify_status)),
    url(r'^update_price', login_required(update_price)),

    url(r'^settings/', login_required(SettingsView.as_view())),
    url(r'^attach_to_user/', attach_to_user),
    url(r'^detach_from_user/', detach_from_user),
    url(r'^set_min_date/', date_filters),
    url(r'^change_min_order/', change_min_order),

    url(r'^add_to_cart/', login_required(add_to_cart)),
    url(r'^delete_from_cart/', login_required(delete_from_cart)),
    url(r'^cart/', login_required(CartView.as_view())),
    url(r'^clear/', login_required(clear)),
    url(r'^update_table/', login_required(get_provider_cart)),
    url(r'^update_quantity', login_required(update_quantity)),

    url(r'^history/', login_required(HistoryView.as_view())),
    url(r'^buy/(?P<i_provider>[\w\-]+)', login_required(CreateOrder.as_view())),

    url(r'^send_again/(?P<order_id>\w+)/', login_required(send_again)),

]

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
# from .models import Product, Price, Provider


class LoginForm(forms.Form):
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }), error_messages={"invalid": "email, который вы ввели неверен"},
                             required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control"
    }), label="Пароль", required=True)

    class Meta:
        model = User

    def login(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(username=email, password=password)
        return user

main/views/CartViews.py
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseBadRequest, HttpRequest

from main.models import Product

from .CommonViews import CommonView
from . import gmail_api_funcs as gaf

from typing import List, Dict, Union
import json


class CartView(CommonView):
    template_name = "cart.html"

    def get_context_data(self, **kwargs)-> dict:
        context = super(CartView, self).get_context_data(**kwargs)
        providers = []
        _providers = []
        for item in context["cart"]:
            provider_info = {"provider": "", "quantity": 0}
            if item["provider"] not in _providers:
                provider_info["provider"] = item["provider"]
                provider_info["quantity"] += 1
                providers.append(provider_info)
                _providers.append(item["provider"])
            else:
                for p_io in providers:
                    if p_io["provider"] == item["provider"]:
                        p_io["quantity"] += 1
        context["providers"] = providers
        context["provider_error"] = self.request.GET.get("error")
        context["error_msg"] = self.request.GET.get("error_msg")
        context["multiplicity_warning"] = self.request.GET.get("multiplicity")
        context["title"] = "cart"
        return context


def get_provider_cart(request: HttpRequest):
    provider = request.GET.get("provider")
    context = {}
    if provider != "":
        cart = request.session.get("cart")
        for item in cart.copy():
            if item["provider"] != provider:
                cart.remove(item)
        context["cart"] = cart
        return HttpResponse(json.dumps(context), content_type="application/json")
    else:
        cart = request.session.get("cart")
        context["cart"] = cart
        return HttpResponse(json.dumps(context), content_type="application/json")


def add_to_cart(request: HttpRequest):
    cart = request.session.get("cart")
    id_product = int(request.GET.get("id"))
    product = Product.objects.get(id=id_product)
    quantity = request.GET.get("quantity")
    a = int(quantity) * float(product.cost)
    item = {"id": id_product, "quantity": int(quantity),
            "name": product.name, "price": product.cost, "sum": "%.2f" % a,
            "provider": str(product.provider), "multiplicity": str(product.multiplicity)
            }
    item_in_cart = check_item(cart, item)
    if not item_in_cart:
        cart.append(item)
        simple_cart: list = request.session.get("simple_cart")
        simple_cart.append(id_product)
        request.session["simple_cart"] = simple_cart
    else:
        cart.remove(item_in_cart)
        item_in_cart["quantity"] += int(item["quantity"])
        item_in_cart["sum"] = item_in_cart["quantity"] * product.cost
        item_in_cart = check_item_quantity(item_in_cart)
        cart.append(item_in_cart)
    request.session["cart"] = cart
    return HttpResponse("Success")


def delete_from_cart(request: HttpRequest):
    cart = request.session.get("cart")
    for item_cart in cart:
        if str(item_cart["id"]) == str(request.GET.get("id")):
            cart.remove(item_cart)
            break
    request.session["cart"] = cart
    simple_cart: List[str] = request.session.get("simple_cart")
    index = simple_cart.index(int(request.GET.get("id")))
    simple_cart.pop(index)
    request.session["simple_cart"] = simple_cart
    return redirect("/cart")


def clear(request: HttpRequest):
    if request.GET.get("provider"):
        simple_cart = request.session.get("simple_cart")
        provider = request.GET.get("provider")
        cart: List[Dict[str, str]] = request.session.get("cart")
        index_array = []
        for item in cart:
            if item.get("provider") == provider:
                simple_cart.pop(simple_cart.index(int(item.get("id"))))
                index = cart.index(item)
                index_array.append(index)
        c = 0
        for index in index_array:
            cart.pop(index-c)
            c += 1
        request.session["cart"] = cart
        request.session["simple_cart"] = simple_cart
        return redirect("/cart/")
    cart: List[Dict[str, str]] = []
    simple_cart = []
    request.session["cart"] = cart
    request.session["simple_cart"] = simple_cart
    if request.GET.get("redir"):
        return redirect(request.GET.get("redir"))
    return redirect('/cart/')


def check_item_quantity(item: Dict[str, str]) -> Union[Dict[str, str], bool]:
    product = Product.objects.get(id=int(item["id"]))
    if product.quantity < int(item["quantity"]):
        item["quantity"] = product.quantity
        item["sum"] = item["quantity"] * product.cost
        return item
    return item


def check_item(cart: List[Dict[str, str]], item: Dict[str, str]) -> Union[Dict[str, str], bool]:
    for cart_item in cart:
        if item["id"] == cart_item["id"]:
            return cart_item
    return False


def update_quantity(request: HttpRequest):
    cart = request.session.get("cart")
    for item_in_cart in cart:
        if item_in_cart.get("id") == int(request.GET.get("id")):
            product = Product.objects.get(id=int(request.GET.get("id")))
            if product.quantity >= int(request.GET.get("quantity")):
                item = item_in_cart
                cart.remove(item_in_cart)
                item["quantity"] = request.GET.get("quantity")
                a = float(item["quantity"]) * float(product.cost)
                item["sum"] = "%.2f" % a
                print(item["sum"])
                cart.append(item)
                request.session["cart"] = cart
                return HttpResponse("succesfull")
            else:
                return HttpResponseBadRequest(product.quantity)


def update_price(request: HttpRequest):
    user: User = request.user
    file_paths = gaf.get_msgs(user)
    for file in file_paths:
        simple_cart = request.session.get("simple_cart")
        provider = file["provider"]
        cart: List[Dict[str, str]] = request.session.get("cart")
        index_array = []
        for item in cart:
            if item.get("provider") == provider.__str__():
                simple_cart.pop(simple_cart.index(int(item.get("id"))))
                index = cart.index(item)
                index_array.append(index)
        c = 0
        for index in index_array:
            cart.pop(index - c)
            c += 1
        request.session["cart"] = cart
        request.session["simple_cart"] = simple_cart
    gaf.create_products(user, file_paths)
    user.new_notifications = 0
    user.is_notified = True
    user.save()
    return redirect("/")

main/views/SettingsViews.py
from django.views.generic import ListView
from django.http import HttpResponse

from main.models import Provider


class SettingsView(ListView):
    model = Provider
    template_name = "settings.html"

    def get_context_data(self, **kwargs):
        context = super(SettingsView, self).get_context_data(**kwargs)
        context["user_providers"] = Provider.objects.all().filter(user=self.request.user)
        print(context["user_providers"])
        context["workers_user"] = Provider.objects.all().filter(work_with=self.request.user)
        context["min_date"] = self.request.session["min_date"]
        context["show"] = self.request.session["show"]
        if self.request.session.get("min_sums") is None:
            min_sums = {}
            self.request.session["min_sums"] = min_sums
        else:
            min_sums = self.request.session["min_sums"]
        context["min_sums"] = min_sums
        context["title"] = "settings"
        return context


def date_filters(request):
    request.session["min_date"] = request.GET.get("time")
    if request.GET.get("show") == "false":
        request.session["show"] = "false"
    else:
        request.session["show"] = "true"
    return HttpResponse("successful")


def attach_to_user(request):
    provider = Provider.objects.get(id=int(request.GET.get("provider")))
    provider.work_with.add(request.user)
    provider.save()
    return HttpResponse("successful")


def detach_from_user(request):
    provider = Provider.objects.get(id=int(request.GET.get("provider")))
    provider.work_with.remove(request.user)
    provider.save()
    return HttpResponse("successful")


def change_min_order(request):
    min_sums = request.session["min_sums"]
    provider = Provider.objects.get(id=int(request.GET["provider"]))
    if request.GET["min_sum"] != "":
        min_sums[str(provider)] = request.GET["min_sum"]
    else:
        min_sums[request.GET["provider"]] = provider.min_order
    request.session["min_sums"] = min_sums
    print(min_sums)
    return HttpResponse("successful")

templates/cart.html
{% extends "index.html" %}
{% block cart %}
    {% if provider_error %}
        <div class="alert alert-danger">
            <strong>Ошибка при заказе у поставщика {{ provider_error }}</strong> Сумма вашего заказа меньше минимального
        </div>
    {% endif %}
    {% if multiplicity_warning and not provider_error %}
        <div class="alert alert-warning">
            <strong>Предупреждение</strong> Не у всех товаров из этого списка совпадает кратность заказать всё равно?
            <a class="btn btn-warning" value="Да" onclick='
            function submit() {
                document.getElementById("ignore_form").value = "1";
                document.getElementById("cart").submit();
            }
            submit()'>Да</a>
            <a class="btn btn-success" value="Нет" href="/cart">Нет</a>
        </div>
    {% endif %}
    {% if error_msg %}
        <div class="alert alert-danger">
            <strong>{{ error_msg }}</strong>
        </div>
    {% endif %}
    <script type="text/javascript">
    function setSum(){
        var sum_elem = document.getElementById('value_s');
        var sum = 0;
        [].forEach.call(document.getElementsByClassName('sum_itema'), function(item) {
            sum += parseFloat(item.innerText);
        });
        sum = Math.round(sum * 100) / 100;
        sum_elem.innerText = "Общая сумма заказа: " + sum + " руб.";
    }
    function updateQuantity(id){
        var sum_elem = document.getElementById("sum_"+id).children[0];
        var price = document.getElementById("current_price_"+id).children[0].innerHTML;
        var q_elem = document.getElementById("QUANTITY_INPUT_" + id);
        var quantity = document.getElementById("QUANTITY_INPUT_" + id).value;
        price = price.split(',')[0] + "." + price.split(',')[1];
        var _sum = parseFloat(price).toFixed(2) * parseInt(quantity).toFixed(2);
        _sum = Math.round(_sum * 100) / 100;
        sum_elem.innerHTML = _sum.toString();
        $.ajax({
            type: "get",
            url: "/update_quantity/",
            data: {
                "id": id,
                "quantity": quantity
            },
            success: function(data){
                setSum();                
            },
            error: function(jqXHR, textStatus, errorThrown){
                q_elem.value = jqXHR.responseText;
                var _sum = parseFloat(price) * parseFloat(q_elem.value);
                sum_elem.innerHTML = _sum.toString();
                setSum();
            }
        })
    }
    function clearCart(){
        location.href = "/clear/";
    }

    function showCartItemsList(elem, provider) {
        [].forEach.call(document.getElementsByClassName("basket_toolbar"), function (item) {
            item.classList.remove("current");
        });
        elem.classList.add("current");
        $.ajax({
            type: "get",
            url: "/update_table/",
            data: {"provider": provider},
            success: function(data){
                provider = provider !== '' ?  provider : 0;
                console.log(provider);
                document.getElementById("cart").setAttribute("action", "/buy/"+provider);
                $("#basket_items_list tbody tr").remove();
                var table = document.getElementById("basket_items_list");
                [].forEach.call(data.cart, function (v) {
                    var row = $("<tr>");
                    row.append($('<td class="margin"></td>'))
                        .append($('<td class="item"></td>').append('<h2 class="bx_ordercart_itemtitle">' + v.name + '</h2>'))
                        .append($('<td class="custom"></td>').append('<div>' + v.provider + '</div>'))
                        .append($('<td class="price"></td>').append($('<div class="current_price" id="current_price_' + v.id + '"></div>')
                                .append('<span class="price_value">' + v.price + '</span>')
                                .append('<span class="price_currency"> руб.</span>')))
                        .append($('<td class="custom"></td>').append($('<div class="centered"></div>')
                                .append($('<table cellspacing="0" cellpadding="0" class="counter"></table>')
                                    .append($('<tbody></tbody>').append($("<tr></tr>")
                                        .append($('<td></td>').append('<input type="text" size="3" id="QUANTITY_INPUT_' + v.id  + '" name="QUANTITY_INPUT_' + v.id + '" maxlength="18" style="max-width: 50px" value="' +  v.quantity + '" onchange="updateQuantity('+ v.id +');">'))
                                        .append($('<td id="basket_quantity_control"></td>').append($('<div class="basket_quantity_control"></div>')
                                            .append('<a href="javascript:void(0);" class="plus" onclick="setQuantity(' + v.id + ', 1,' + "'up'" + ', false)"></a>')
                                            .append('<a href="javascript:void(0);" class="minus" onclick="setQuantity(' + v.id + ', 1,' + "'down'" + ', false)"></a>')
                                        ))
                                    ))
                                )
                        ))
                        .append($('<td class="custom"></td>').append($('<div id="sum_' + v.id + '"></div>')
                                .append('<span class="price_value sum_itema">' + v.sum + '</span>')
                                .append('<span class="price_currency"> руб.</span>')))
                        .append($('<td class="control"></td>')
                            .append('<a href="/delete_from_cart/?id=' + v.id +'" onclick="return deleteProductRow(this)">Удалить</a>')
                            .append('<a style="display: none;"></a>'))
                        .append($('<td class="margin"></td>'));
                    $("#basket_list").append(row);
                    setSum();
                })
            }
        })
    }
    </script>
    <form action="/buy/0" method="post" xmlns="" id="cart">
        {% csrf_token %}
        <input type="hidden" name="ignore" value="" id="ignore_form">
        <div id="basket_form_container">
            <div class="bx_ordercart bx_blue">
                <div class="bx_sort_container">
                    <a href="javascript:void(0)" class="current basket_toolbar" onclick="showCartItemsList(this, '');">
                        Все
                        <div id="normal_count" class="flat" style="display: none">({{ cart|length }})</div>
                    </a>
                    {% for provider in providers %}
                        <a href="javascript:void(0)" class="basket_toolbar" onclick="showCartItemsList(this, '{{ provider.provider }}');">
                            {{ provider.provider }}
                            <div id="normal_count" class="flat" style="display: none;">({{ provider.quantity }})</div>
                        </a>
                    {% endfor %}
                    <div class="top_control basket_sort">
                        <span class="delete_all button grey_br transparent remove_all_basket" onclick="clearCart();">Очистить</span>
                    </div>
                </div>
                <div id="basket_items_list">
                    <div class="bx_ordercart_order_table_container">
                        <table id="basket_items">
                            <thead>
                                <td class="margin"></td>
                                <td class="item" colspan="1" id="col_NAME" >Товары</td>
                                <td class="custom">Поставщик</td>
                                <td class="price" id="col_PRICE">Цена</td>
                                <td class="custom" id="col_QUANTITY">Количество</td>
                                <td class="custom" id="col_SUM">Сумма</td>
                                <td class="custom"></td>
                                <td class="margin"></td>
                            </thead>
                            <tbody id="basket_list">
                                {% for item in cart %}
                                    <tr>
                                        <td class="margin"></td>
                                        <td class="item">
                                            <h2 class="bx_ordercart_itemtitle">{{ item.name }}</h2>
                                        </td>
                                        <td class="custom">
                                            <div>{{ item.provider }}</div>
                                        </td>
                                        <td class="price">
                                            <div class="current_price" id="current_price_{{ item.id }}">
                                                <span class="price_value">{{ item.price }}</span>
                                                <span class="price_currency"> руб.</span>
                                            </div>
                                        </td>
                                        <td class="custom">
                                            <div class="centered">
                                                <table cellpadding="0" cellspacing="0" class="counter">
                                                    <tbody>
                                                        <tr>
                                                            <td>
                                                                <input type="text" size="3" id="QUANTITY_INPUT_{{ item.id }}"
                                                                name="QUANTITY_INPUT_{{ item.id }}" maxlength="18"
                                                                style="max-width: 50px" value="{{ item.quantity }}"
                                                                onchange="updateQuantity({{ item.id }});">
                                                            </td>
                                                            <td id="basket_quantity_control">
                                                                <div class="basket_quantity_control">
                                                                    <a href="javascript:void(0);" class="plus"
                                                                       onclick="setQuantity({{ item.id }}, {{ item.multiplicity }}, 'up', false)">
                                                                    </a>
                                                                    <a href="javascript:void(0);" class="minus"
                                                                       onclick="setQuantity({{ item.id }}, {{ item.multiplicity }}, 'down', false)">
                                                                    </a>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </td>
                                        <td class="custom">
                                            <div id="sum_{{ item.id }}">
                                                <span class="price_value sum_itema">{{ item.sum }}</span>
                                                <span class="price_currency"> руб.</span>
                                            </div>
                                        </td>
                                        <td class="control">
                                            <a href="/delete_from_cart/?id={{ item.id }}" onclick="return deleteProductRow(this)">Удалить</a>
                                            <a style="display: none;"></a>
                                        </td>
                                        <td class="margin"></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="bx_ordercart_order_pay">
                        <div class="bx_ordercart_order_pay_center">
                            <a href="/catalog" class="catalog_back button transparent big_btn grey_br">Продолжить покупки</a>
                            <span class="price_value" id="value_s"><script type="text/javascript">setSum()</script></span>
                            <a href="javascript:{}" onclick="document.getElementById('cart').submit()" class="oneclickbuy button big_btn fast_order">Оформить заказ</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/history.html
{% extends "index.html" %}

{% block history %}
    <script>
    function toggleFunc(elem) {
        [].forEach.call(document.getElementsByClassName("item_"+elem.id), function (v, i, a) {
            console.log(v);
            if (v.classList.contains("hide")){
                v.classList.remove("hide");
            } else {
                v.classList.add("hide");
            }
        });

    }
    </script>
    <div class="ajax_load table">
        <table class="module_products_list" style="border-collapse: separate">
            {% for order in orders %}
                <tr class="item" id="bx_3966226736_{{ order.id }}">
                    <td class="item-name-cell">
                        <div class="title"><a>{{ order.id }}</a></div>
                    </td>
                    <td class="item-name-cell">
                        <div class="title" style="font-size: 14px; color: black">
                            <a href="/search/?q={{ query }}&provider={{ result.price.provider.id }}"></a>
                        </div>
                    </td>
                    <td class="price-cell">
                        <div class="cost prices clearfix">
                            <div class="price">
                                <span class='price_value'>{{ order.get_summary }}</span>
                                <span class='price_currency'> руб.</span>
                            </div>
                        </div>
                    </td>
                    <td class="price-cell">
                        <div class="cost prices">
                            <div class="price">
                                <span class='price_value'>{{ order.get_product_set|length }}</span>
                                <span class='price_currency'> шт.</span>
                            </div>
                        </div>
                    </td>
                    <td class="price-cell">
                        <div class="cost prices">
                            <span class="price_value">{{ order.date }}</span>
                        </div>
                    </td>
                    <td style="max-width: 200px; text-align: left; width: 5%;">
                        <a id="{{ order.id }}" onclick="toggleFunc(this);"><span class="glyphicon glyphicon-chevron-down"></span></a>
                    </td>
                </tr>
                {% for product in order.get_product_set %}
                    <tr class="item hide item_{{ order.id }}">
                    <td class="item-name-cell">
                        <div class="title"><a href="">{{ product.name }}</a></div>
                    </td>
                    <td class="item-name-cell">{{ product.provider }}</td>
                    <td class="price-cell">
                        <div class="cost prices clearfix">
                            <div class="price">
                                <span class='price_value'>{{ product.cost }}</span>
                                <span class='price_currency'> руб.</span>
    {#                        <div class="price discount">#}
    {#                            <span>#}
    {#                                <span class='price_value'>5 990</span><span class='price_currency'> руб.</span>#}
    {#                            </span>#}
    {#                        </div>#}
                            </div>
                        </div>
                    </td>
                    <td class="price-cell">
                        <div class="cost prices">
                            <div class="price">
                                <span class='price_value'>{{ product.quantity }}</span>
                                <span class='price_currency'> шт.</span>
                            </div>
                        </div>
                    </td>
                    <td class="price-cell" style="max-width: 200px; text-align: left; width: 21%">
                        <div class="cost prices">
                            <div class="price">
                                <span class="price_value">{{ product.get_summary }}</span>
                                <span class='price_currency'> руб.</span>
                            </div>
                        </div>
                    </td>
                    <td></td>
                </tr>
                {% endfor %}
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/login.html
<html>
<head>
    <meta charset="utf-8">
    <title>Вход</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body{
            background: #fefefe;
            margin: 0;
            padding: 0;
{#            font: 1em/1.3em Ubuntu, Arial, Helvetica, sans-serif;#}
            color: #272727;
        }
        .main{
            margin: 20px;
{#            border: 1px solid #ccc;#}
            padding: 20px;
            background: #fff;
            border-radius: 3px;
        }
        .main{
            display: -webkit-box;
            display: -webkit-flex;
            display: -ms-flexbox;
            display: flex;
            align-items: flex-start;
            max-width: 500px;
            align-content: center;
            margin: 200px auto;
            flex-flow: row wrap;
        }
        .login_form{
            padding: 5px 10px;
{#            border: 1px solid #ddd;#}
{#            background: #fffde1;#}
            border-radius: 3px;
            margin: 20px;
            width: 100%;
            justify-content: space-around;
        }
        .butsub{
            height: 50px;
            padding: 5px 0;
            margin: 20px 0;
        }
        .email{
            height: 50px;
            padding: 5px 0;
            margin: 10px 0;
        }
        .pwd{
            height: 50px;
            padding: 5px 0;
            margin: 10px 0;
        }
        .errorlist{
            padding: 0;
            list-style-type: none;
        }
        .errorlist li{
            display: block;
            color: red;
            font-style: italic;
        }
    </style>
</head>
<body>
<div class="main">
    <div class="login_form">
        <form action="/" method="post">
            {% csrf_token %}
            {% for key, value in form.errors.items %}
                {{ value }}
            {% endfor %}
            <div class="email">
                <label for="id_email">Email</label>
                {{ form.email }}
            </div>
            <div class="pwd">
                <label for="id_password">Пароль</label>
                {{ form.password }}
            </div>
            <div class="butsub">
                <input type="submit" value="Войти" class="form-control btn-success">
            </div>
        </form>
    </div>
</div>
</body>
</html>